---
name: HubDelay
version: 0.0.2
main: BagiCraft01\HubDelay\Main
api: [3.0.0]
load: POSTWORLD

author: sProDev <suluh@teknowebapp.com>
website: https://suluh.my.id/

commands:
  hub:
    description: "Teleport to HUB"
...
